from typing import List, Union


class ScalingRule:
    """
    A rule that defines position scaling behavior for a specific symbol.

    Position scaling allows a strategy to add to an existing position
    (scale in / pyramid) or partially close a position (scale out)
    based on signals generated by the strategy.

    When a ScalingRule is defined for a symbol, the strategy flow becomes:
        1. No position → buy signal opens with the full PositionSize
        2. Has position → scale_in signal adds scale_in_percentage of
           the original PositionSize (up to max_entries total entries)
        3. Has position → scale_out signal partially closes
           scale_out_percentage of the current position
        4. Has position → sell signal fully closes the position
           (always takes priority over scale-out)

    Without a ScalingRule, behavior is identical to the default:
    one entry, one full exit.

    Attributes:
        symbol (str): The target symbol this rule applies to (e.g. "BTC").
        max_entries (int): Maximum number of entries (including the initial
            buy). Default 1 means no pyramiding. Set to 3 to allow
            the initial entry plus 2 scale-ins.
        scale_in_percentage (float | List[float]): Size of each scale-in
            as a percentage of the original PositionSize. Can be a single
            float (same for all scale-ins) or a list (one per scale-in).
            If the list is shorter than the number of scale-ins, the last
            value is reused. Default 100.
            Examples:
                scale_in_percentage=50       → each add is 50% of original
                scale_in_percentage=[50, 25] → 1st add 50%, 2nd add 25%
        scale_out_percentage (float | List[float]): Percentage of the
            current position to sell on a scale-out signal. Can be a
            single float or a list (one per consecutive scale-out).
            If the list is shorter, the last value is reused. Default 50.
            Examples:
                scale_out_percentage=50       → sell 50% each time
                scale_out_percentage=[25, 50] → 1st trim 25%, 2nd trim 50%
        max_position_percentage (float | None): Maximum total position
            size as a percentage of the portfolio. None means no cap.
            When set, scale-in orders will be reduced or skipped if
            they would exceed this cap.
        cooldown_in_bars (int): Number of bars to wait after a buy or
            sell action before the next signal for this symbol is acted
            upon. Default 0 means no cooldown. This filters out noise
            from rapid signals.
    """

    def __init__(
        self,
        symbol: str,
        max_entries: int = 1,
        scale_in_percentage: Union[float, List[float]] = 100,
        scale_out_percentage: Union[float, List[float]] = 50,
        max_position_percentage: float = None,
        cooldown_in_bars: int = 0,
    ):
        self.symbol = symbol
        self.max_entries = max_entries
        self.max_position_percentage = max_position_percentage
        self.cooldown_in_bars = cooldown_in_bars

        # Normalize to list internally
        if isinstance(scale_in_percentage, (int, float)):
            self._scale_in_percentages = [float(scale_in_percentage)]
        else:
            self._scale_in_percentages = [
                float(v) for v in scale_in_percentage
            ]

        if isinstance(scale_out_percentage, (int, float)):
            self._scale_out_percentages = [float(scale_out_percentage)]
        else:
            self._scale_out_percentages = [
                float(v) for v in scale_out_percentage
            ]

    @property
    def scale_in_percentage(self) -> Union[float, List[float]]:
        if len(self._scale_in_percentages) == 1:
            return self._scale_in_percentages[0]
        return list(self._scale_in_percentages)

    @property
    def scale_out_percentage(self) -> Union[float, List[float]]:
        if len(self._scale_out_percentages) == 1:
            return self._scale_out_percentages[0]
        return list(self._scale_out_percentages)

    def get_scale_in_percentage(self, entry_index: int) -> float:
        """
        Get the scale-in percentage for the nth scale-in (0-indexed).

        Args:
            entry_index: The 0-based index of the scale-in
                (0 = first scale-in after initial entry).

        Returns:
            The percentage to use for this scale-in.
        """
        if entry_index < len(self._scale_in_percentages):
            return self._scale_in_percentages[entry_index]
        return self._scale_in_percentages[-1]

    def get_scale_out_percentage(self, scale_out_index: int) -> float:
        """
        Get the scale-out percentage for the nth scale-out (0-indexed).

        Args:
            scale_out_index: The 0-based index of the scale-out
                (0 = first scale-out signal).

        Returns:
            The percentage to use for this scale-out.
        """
        if scale_out_index < len(self._scale_out_percentages):
            return self._scale_out_percentages[scale_out_index]
        return self._scale_out_percentages[-1]

    def __repr__(self) -> str:
        return (
            f"ScalingRule(symbol={self.symbol}, "
            f"max_entries={self.max_entries}, "
            f"scale_in_percentage={self.scale_in_percentage}, "
            f"scale_out_percentage={self.scale_out_percentage}, "
            f"max_position_percentage={self.max_position_percentage}, "
            f"cooldown_in_bars={self.cooldown_in_bars})"
        )
