# Naming conventions
FRAMEWORK_NAME = 'investing_algorithm_framework'
FRAMEWORK_CORE_MODULE_NAME = 'investing_algorithm_framework.core'
SETTINGS_MODULE_PATH_ENV_NAME = 'INVESTING_ALGORITHM_FRAMEWORK_SETTINGS_MODULE'

# Project related constants
BASE_DIR = 'BASE_DIR'
SETTINGS_PROJECT_NAME = 'PROJECT_NAME'
SETTINGS_MAX_CONCURRENT_WORKERS = 'MAX_CONCURRENT_WORKERS'
SETTINGS_CONTEXT_CONFIGURATION = 'CONTEXT_CONFIGURATION'
SETTINGS_LOGGING_CONFIG = 'LOGGING'

# Database related constants
DATABASE_CONFIG = 'DATABASE_CONFIG'
DATABASE_NAME = 'DATABASE_NAME'
DATABASE_TYPE = 'DATABASE_TYPE'
DATABASE_DIRECTORY_PATH = 'DATABASE_DIRECTORY_PATH'
DATABASE_URL = 'DATABASE_URL'

DEFAULT_MAX_WORKERS = 2
