# Naming conventions
FRAMEWORK_NAME = 'investing bot framework'
FRAMEWORK_CORE_MODULE_NAME = 'bot.core'

# Setting related constants
SETTINGS_BOT_PROJECT_NAME = 'BOT_PROJECT_NAME'
SETTINGS_MODULE_PATH_ENV_NAME = 'INVESTING_BOT_FRAMEWORK_SETTINGS_MODULE'
SETTINGS_DATA_PROVIDER_REGISTERED_APPS = 'INSTALLED_DATA_PROVIDER_APPS'
SETTINGS_STRATEGY_REGISTERED_APPS = 'INSTALLED_STRATEGY_APPS'
