blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/coding-kitties/investing-algorithm-framework#readme
    about: Check the documentation before opening an issue.
