"""Limit-order executor — v9.0 default.

Routes every intent through ``context.create_limit_order``
(long side) or ``context.create_short_order`` /
``create_cover_order`` with ``order_type=LIMIT`` (short side).

This preserves the pre-v9 behaviour of ``TradingStrategy``: every
order generated by the phase pipeline is a limit order pegged at
the latest price discovered in :class:`SizePositionsPhase`.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from investing_algorithm_framework.domain.models.order import OrderType
from investing_algorithm_framework.services.strategy_phases import phase_state

from .base import Executor


class LimitOrderExecutor(Executor):
    """Place limit orders for every intent."""

    short_order_type: OrderType = OrderType.LIMIT

    def _long_buy(
        self,
        intent: phase_state.SizedIntent,
        context: Any,
        metadata: Dict[str, Any],
    ) -> Optional[Any]:
        return context.create_limit_order(
            target_symbol=intent.symbol,
            order_side=self._buy_side(),
            amount=intent.amount,
            price=intent.price,
            execute=True,
            validate=True,
            sync=True,
            metadata=metadata,
        )

    def _long_sell(
        self,
        intent: phase_state.SizedIntent,
        context: Any,
        metadata: Dict[str, Any],
    ) -> Optional[Any]:
        return context.create_limit_order(
            target_symbol=intent.symbol,
            order_side=self._sell_side(),
            amount=intent.amount,
            price=intent.price,
            execute=True,
            validate=True,
            sync=True,
            metadata=metadata,
        )
